<?php

namespace Database\Seeders;

use App\Models\Cities;
use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Cities::truncate();

        $cities = array(
            array('name' => "Bombuflat", 'state_id' => 1),
            array('name' => "Bechem", 'state_id' => 1),
            array('name' => "Duayaw Nkwantah", 'state_id' => 1),
            array('name' => "Goaso", 'state_id' => 1),
            array('name' => "Hwidiem", 'state_id' => 1),
            array('name' => "Kenyasi", 'state_id' => 1),
            array('name' => "Kukuom", 'state_id' => 1),
            array('name' => "Abrepo Junction", 'state_id' => 2),
            array('name' => "Abuakwa", 'state_id' => 2),
            array('name' => "Adum", 'state_id' => 2),
            array('name' => "Afrancho", 'state_id' => 2),
            array('name' => "Agogo", 'state_id' => 2),
            array('name' => "Agona", 'state_id' => 2),
            array('name' => "Ahodwo", 'state_id' => 2),
            array('name' => "Airport", 'state_id' => 2),
            array('name' => "Akumadan", 'state_id' => 2),
            array('name' => "Amakom", 'state_id' => 2),
            array('name' => "Aputuogya", 'state_id' => 2),
            array('name' => "Asafo", 'state_id' => 2),
            array('name' => "Ash-Town", 'state_id' => 2),
            array('name' => "Asokore Mampong", 'state_id' => 2),
            array('name' => "Asokwa", 'state_id' => 2),
            array('name' => "Asuofia", 'state_id' => 2),
            array('name' => "Atonsu", 'state_id' => 2),
            array('name' => "Ayeduasi", 'state_id' => 2),
            array('name' => "Ayigya", 'state_id' => 2),
            array('name' => "Bantama", 'state_id' => 2),
            array('name' => "Barekese", 'state_id' => 2),
            array('name' => "Bekwai", 'state_id' => 2),
            array('name' => "Boadi", 'state_id' => 2),
            array('name' => "Bomso", 'state_id' => 2),
            array('name' => "Breman", 'state_id' => 2),
            array('name' => "Brewery", 'state_id' => 2),
            array('name' => "Buoho", 'state_id' => 2),
            array('name' => "Buokrom Estate", 'state_id' => 2),
            array('name' => "Daban", 'state_id' => 2),
            array('name' => "Dakwadwom", 'state_id' => 2),
            array('name' => "Deduako", 'state_id' => 2),
            array('name' => "Denyame", 'state_id' => 2),
            array('name' => "Effiduase", 'state_id' => 2),
            array('name' => "Ejisu", 'state_id' => 2),
            array('name' => "Ejura", 'state_id' => 2),
            array('name' => "Emina", 'state_id' => 2),
            array('name' => "Esreso", 'state_id' => 2),
            array('name' => "Fawode", 'state_id' => 2),
            array('name' => "Gyinyasi", 'state_id' => 2),
            array('name' => "Jachie Pramso", 'state_id' => 2),
            array('name' => "Kaasi", 'state_id' => 2),
            array('name' => "KNUST", 'state_id' => 2),
            array('name' => "Kodie", 'state_id' => 2),
            array('name' => "Komfo Anokye", 'state_id' => 2),
            array('name' => "Konongo", 'state_id' => 2),
            array('name' => "Kotei", 'state_id' => 2),
            array('name' => "Krofrom", 'state_id' => 2),
            array('name' => "Kumasi", 'state_id' => 2),
            array('name' => "Maakro", 'state_id' => 2),
            array('name' => "Mampong", 'state_id' => 2),
            array('name' => "Mankranso", 'state_id' => 2),
            array('name' => "Manso Nkwanta", 'state_id' => 2),
            array('name' => "Nkawie", 'state_id' => 2),
            array('name' => "North Suntreso", 'state_id' => 2),
            array('name' => "Nyinahin", 'state_id' => 2),
            array('name' => "Obuasi", 'state_id' => 2),
            array('name' => "Oforikrom", 'state_id' => 2),
            array('name' => "Pankrono", 'state_id' => 2),
            array('name' => "Santasi", 'state_id' => 2),
            array('name' => "Sokoban", 'state_id' => 2),
            array('name' => "South Suntreso", 'state_id' => 2),
            array('name' => "Suame", 'state_id' => 2),
            array('name' => "Tafo", 'state_id' => 2),
            array('name' => "Takwa-Maakro", 'state_id' => 2),
            array('name' => "Tanoso", 'state_id' => 2),
            array('name' => "Tepa", 'state_id' => 2),
            array('name' => "TUC", 'state_id' => 2),
            array('name' => "Amomaso", 'state_id' => 3),
            array('name' => "Banda Ahenkro", 'state_id' => 3),
            array('name' => "Berekum", 'state_id' => 3),
            array('name' => "Benkasa", 'state_id' => 3),
            array('name' => "Chiraa", 'state_id' => 3),
            array('name' => "Dormaa Ahenkro", 'state_id' => 3),
            array('name' => "Dormaa Akwamu", 'state_id' => 3),
            array('name' => "Drobo", 'state_id' => 3),
            array('name' => "Fiapre", 'state_id' => 3),
            array('name' => "Jinijini", 'state_id' => 3),
            array('name' => "New Drobo", 'state_id' => 3),
            array('name' => "Nkrankwanta", 'state_id' => 3),
            array('name' => "Nsawkaw", 'state_id' => 3),
            array('name' => "Nsuatre", 'state_id' => 3),
            array('name' => "Odumase", 'state_id' => 3),
            array('name' => "Sampa", 'state_id' => 3),
            array('name' => "Seikwa", 'state_id' => 3),
            array('name' => "Sunyani", 'state_id' => 3),
            array('name' => "Wamfie", 'state_id' => 3),
            array('name' => "Atebubu", 'state_id' => 4),
            array('name' => "Buipe", 'state_id' => 4),
            array('name' => "Jema", 'state_id' => 4),
            array('name' => "Kintampo", 'state_id' => 4),
            array('name' => "Kwame Danso", 'state_id' => 4),
            array('name' => "Nkoranza", 'state_id' => 4),
            array('name' => "Prang", 'state_id' => 4),
            array('name' => "Techiman", 'state_id' => 4),
            array('name' => "Tuobodom", 'state_id' => 4),
            array('name' => "Wenchi", 'state_id' => 4),
            array('name' => "Yeji", 'state_id' => 4),
            array('name' => "Agona Swedru", 'state_id' => 5),
            array('name' => "Amanfrom", 'state_id' => 5),
            array('name' => "Anomabu", 'state_id' => 5),
            array('name' => "Apam", 'state_id' => 5),
            array('name' => "Bawjiase", 'state_id' => 5),
            array('name' => "Breman Asikuma", 'state_id' => 5),
            array('name' => "Budumburam", 'state_id' => 5),
            array('name' => "Cape Coast", 'state_id' => 5),
            array('name' => "Domeabra", 'state_id' => 5),
            array('name' => "Elmina", 'state_id' => 5),
            array('name' => "Foso", 'state_id' => 5),
            array('name' => "Kasoa Ofaakor", 'state_id' => 5),
            array('name' => "Kasoa Zongo", 'state_id' => 5),
            array('name' => "Liberia Camp", 'state_id' => 5),
            array('name' => "Mankessim", 'state_id' => 5),
            array('name' => "Millennium City", 'state_id' => 5),
            array('name' => "Mumford", 'state_id' => 5),
            array('name' => "Nyakrom", 'state_id' => 5),
            array('name' => "Nyananor", 'state_id' => 5),
            array('name' => "Nyanyano", 'state_id' => 5),
            array('name' => "Oduponkpehe", 'state_id' => 5),
            array('name' => "Opeikuma", 'state_id' => 5),
            array('name' => "Pentecost Seminary", 'state_id' => 5),
            array('name' => "Saltpond", 'state_id' => 5),
            array('name' => "Winneba", 'state_id' => 5),
            array('name' => "Abetifi", 'state_id' => 6),
            array('name' => "Abompe", 'state_id' => 6),
            array('name' => "Aburi", 'state_id' => 6),
            array('name' => "Adeiso", 'state_id' => 6),
            array('name' => "Adjeiikrom", 'state_id' => 6),
            array('name' => "Adukrom", 'state_id' => 6),
            array('name' => "Ahwerease", 'state_id' => 6),
            array('name' => "Akim Oda", 'state_id' => 6),
            array('name' => "Akim Swedru", 'state_id' => 6),
            array('name' => "Akosombo", 'state_id' => 6),
            array('name' => "Akropong", 'state_id' => 6),
            array('name' => "Akwatia", 'state_id' => 6),
            array('name' => "Akyem Hemang", 'state_id' => 6),
            array('name' => "Amanokrom", 'state_id' => 6),
            array('name' => "Apirede", 'state_id' => 6),
            array('name' => "Asamankese", 'state_id' => 6),
            array('name' => "Asesewa", 'state_id' => 6),
            array('name' => "Atimpoku", 'state_id' => 6),
            array('name' => "Ayiensu", 'state_id' => 6),
            array('name' => "Begoro", 'state_id' => 6),
            array('name' => "Bepoase", 'state_id' => 6),
            array('name' => "Bisibom", 'state_id' => 6),
            array('name' => "Bososo", 'state_id' => 6),
            array('name' => "Brekusu", 'state_id' => 6),
            array('name' => "Coaltar", 'state_id' => 6),
            array('name' => "Dawu", 'state_id' => 6),
            array('name' => "Dedesoworako", 'state_id' => 6),
            array('name' => "Donkorkrom", 'state_id' => 6),
            array('name' => "Dwenase", 'state_id' => 6),
            array('name' => "Gyankama", 'state_id' => 6),
            array('name' => "Juaso", 'state_id' => 6),
            array('name' => "Kade", 'state_id' => 6),
            array('name' => "Kibi", 'state_id' => 6),
            array('name' => "Kitase", 'state_id' => 6),
            array('name' => "Koforidua", 'state_id' => 6),
            array('name' => "Kwabeng", 'state_id' => 6),
            array('name' => "Mamfe", 'state_id' => 6),
            array('name' => "Mampong", 'state_id' => 6),
            array('name' => "Mpraeso", 'state_id' => 6),
            array('name' => "New Abirem", 'state_id' => 6),
            array('name' => "Nkawkaw", 'state_id' => 6),
            array('name' => "Nsawam", 'state_id' => 6),
            array('name' => "Nsutam", 'state_id' => 6),
            array('name' => "Obooho", 'state_id' => 6),
            array('name' => "Obosomase", 'state_id' => 6),
            array('name' => "Odumase Krobo", 'state_id' => 6),
            array('name' => "Ofoase", 'state_id' => 6),
            array('name' => "Osino", 'state_id' => 6),
            array('name' => "Peduase", 'state_id' => 6),
            array('name' => "Saaman", 'state_id' => 6),
            array('name' => "Somanya", 'state_id' => 6),
            array('name' => "Summer", 'state_id' => 6),
            array('name' => "Suhum", 'state_id' => 6),
            array('name' => "Tease", 'state_id' => 6),
            array('name' => "Tutu", 'state_id' => 6),
            array('name' => "Abelemkpe", 'state_id' => 7),
            array('name' => "Ablekuma", 'state_id' => 7),
            array('name' => "Abokobi", 'state_id' => 7),
            array('name' => "Abossey Okai", 'state_id' => 7),
            array('name' => "Accra Newtown", 'state_id' => 7),
            array('name' => "Achimota", 'state_id' => 7),
            array('name' => "Adabraka", 'state_id' => 7),
            array('name' => "Adenta", 'state_id' => 7),
            array('name' => "Afienya", 'state_id' => 7),
            array('name' => "Agbogba", 'state_id' => 7),
            array('name' => "Airport", 'state_id' => 7),
            array('name' => "Amasaman", 'state_id' => 7),
            array('name' => "Ashiaman", 'state_id' => 7),
            array('name' => "Ashongman", 'state_id' => 7),
            array('name' => "Aslyum Down", 'state_id' => 7),
            array('name' => "Atico", 'state_id' => 7),
            array('name' => "Baatsona - Spintex", 'state_id' => 7),
            array('name' => "Bortianor", 'state_id' => 7),
            array('name' => "Cantonment", 'state_id' => 7),
            array('name' => "Dansoman", 'state_id' => 7),
            array('name' => "Darkuman", 'state_id' => 7),
            array('name' => "Dawhenya", 'state_id' => 7),
            array('name' => "Dodowa", 'state_id' => 7),
            array('name' => "Dome", 'state_id' => 7),
            array('name' => "Dzorwulu", 'state_id' => 7),
            array('name' => "East Legon", 'state_id' => 7),
            array('name' => "Gbawe", 'state_id' => 7),
            array('name' => "Haatso", 'state_id' => 7),
            array('name' => "James Town", 'state_id' => 7),
            array('name' => "Kanda", 'state_id' => 7),
            array('name' => "Kaneshie", 'state_id' => 7),
            array('name' => "Kasoa", 'state_id' => 7),
            array('name' => "Kissieman", 'state_id' => 7),
            array('name' => "Kokrobite", 'state_id' => 7),
            array('name' => "Korle Bu", 'state_id' => 7),
            array('name' => "Kpone", 'state_id' => 7),
            array('name' => "Kwabenya", 'state_id' => 7),
            array('name' => "Kwashieman", 'state_id' => 7),
            array('name' => "Suiano", 'state_id' => 16),
            array('name' => "Labadi", 'state_id' => 7),
            array('name' => "Labone", 'state_id' => 7),
            array('name' => "Lapaz", 'state_id' => 7),
            array('name' => "Lartebiokorshie", 'state_id' => 7),
            array('name' => "Lashibi", 'state_id' => 7),
            array('name' => "Legon", 'state_id' => 7),
            array('name' => "Madina", 'state_id' => 7),
            array('name' => "Makola", 'state_id' => 7),
            array('name' => "Mallam", 'state_id' => 7),
            array('name' => "McCarthy Hill", 'state_id' => 7),
            array('name' => "Michel Camp", 'state_id' => 7),
            array('name' => "Nima", 'state_id' => 7),
            array('name' => "Nungua", 'state_id' => 7),
            array('name' => "Oblogo Mallam", 'state_id' => 7),
            array('name' => "Odoponkpehe", 'state_id' => 7),
            array('name' => "Odorkor", 'state_id' => 7),
            array('name' => "Osu", 'state_id' => 7),
            array('name' => "Oyarifa", 'state_id' => 7),
            array('name' => "Patang", 'state_id' => 7),
            array('name' => "Prampram", 'state_id' => 7),
            array('name' => "Ridge", 'state_id' => 7),
            array('name' => "Roman Ridge", 'state_id' => 7),
            array('name' => "Sakumono", 'state_id' => 7),
            array('name' => "Santa Maria", 'state_id' => 7),
            array('name' => "Sowutuom", 'state_id' => 7),
            array('name' => "Taifa", 'state_id' => 7),
            array('name' => "Tema", 'state_id' => 7),
            array('name' => "Tema New Town", 'state_id' => 7),
            array('name' => "Tesano", 'state_id' => 7),
            array('name' => "Teshie", 'state_id' => 7),
            array('name' => "Tetegu", 'state_id' => 7),
            array('name' => "Tieman", 'state_id' => 7),
            array('name' => "Tudu", 'state_id' => 7),
            array('name' => "Weija", 'state_id' => 7),
            array('name' => "Westhills", 'state_id' => 7),
            array('name' => "Chereponi", 'state_id' => 8),
            array('name' => "Gambaga", 'state_id' => 8),
            array('name' => "Nalerigu", 'state_id' => 8),
            array('name' => "Walewale", 'state_id' => 8),
            array('name' => "Bimbila", 'state_id' => 9),
            array('name' => "Gushiegu", 'state_id' => 9),
            array('name' => "Kpandae", 'state_id' => 9),
            array('name' => "Saboba", 'state_id' => 9),
            array('name' => "Salaga", 'state_id' => 9),
            array('name' => "Tamale", 'state_id' => 9),
            array('name' => "Tatale", 'state_id' => 9),
            array('name' => "Wulensi", 'state_id' => 9),
            array('name' => "Yendi", 'state_id' => 9),
            array('name' => "Chinderi", 'state_id' => 10),
            array('name' => "Jasikan", 'state_id' => 10),
            array('name' => "Kadjebi", 'state_id' => 10),
            array('name' => "Kete Krachi", 'state_id' => 10),
            array('name' => "Kpassa", 'state_id' => 10),
            array('name' => "Nkonya", 'state_id' => 10),
            array('name' => "Bole", 'state_id' => 11),
            array('name' => "Buipe", 'state_id' => 11),
            array('name' => "Damango", 'state_id' => 11),
            array('name' => "Salaga", 'state_id' => 11),
            array('name' => "Sawla", 'state_id' => 11),
            array('name' => "Tolon", 'state_id' => 11),
            array('name' => "Bawku", 'state_id' => 12),
            array('name' => "Bolgatanga", 'state_id' => 12),
            array('name' => "Bongo", 'state_id' => 12),
            array('name' => "Navrongo", 'state_id' => 12),
            array('name' => "Paga", 'state_id' => 12),
            array('name' => "Tongo", 'state_id' => 12),
            array('name' => "Funsi", 'state_id' => 13),
            array('name' => "Gwollu", 'state_id' => 13),
            array('name' => "Issa", 'state_id' => 13),
            array('name' => "Jirapa", 'state_id' => 13),
            array('name' => "Kaleo", 'state_id' => 13),
            array('name' => "Lambussie", 'state_id' => 13),
            array('name' => "Lawra", 'state_id' => 13),
            array('name' => "Nadowli", 'state_id' => 13),
            array('name' => "Nandom", 'state_id' => 13),
            array('name' => "Tumu", 'state_id' => 13),
            array('name' => "Wa", 'state_id' => 13),
            array('name' => "Wechiau", 'state_id' => 13),
            array('name' => "Adaklu Waya", 'state_id' => 14),
            array('name' => "Adidome", 'state_id' => 14),
            array('name' => "Aflao", 'state_id' => 14),
            array('name' => "Agbozume", 'state_id' => 14),
            array('name' => "Akatsi", 'state_id' => 14),
            array('name' => "Ave Dakpa", 'state_id' => 14),
            array('name' => "Ho.", 'state_id' => 14),
            array('name' => "Hohoe", 'state_id' => 14),
            array('name' => "Keta", 'state_id' => 14),
            array('name' => "klikor", 'state_id' => 14),
            array('name' => "Kpando", 'state_id' => 14),
            array('name' => "Kpetoe", 'state_id' => 14),
            array('name' => "Kpeve", 'state_id' => 14),
            array('name' => "Sogakope", 'state_id' => 14),
            array('name' => "Abase", 'state_id' => 15),
            array('name' => "Aboso", 'state_id' => 15),
            array('name' => "Adiawoso", 'state_id' => 15),
            array('name' => "Adiembra", 'state_id' => 15),
            array('name' => "Adwowa", 'state_id' => 15),
            array('name' => "Agona Nkwanta", 'state_id' => 15),
            array('name' => "Agufo", 'state_id' => 15),
            array('name' => "Ahonozo", 'state_id' => 15),
            array('name' => "Akatachi", 'state_id' => 15),
            array('name' => "Alabokazo", 'state_id' => 15),
            array('name' => "Anaji", 'state_id' => 15),
            array('name' => "Apowa", 'state_id' => 15),
            array('name' => "Apremodo", 'state_id' => 15),
            array('name' => "Asankragua", 'state_id' => 15),
            array('name' => "Awukyere", 'state_id' => 15),
            array('name' => "Axim", 'state_id' => 15),
            array('name' => "Beahu", 'state_id' => 15),
            array('name' => "Bogoso", 'state_id' => 15),
            array('name' => "Butumagyabu", 'state_id' => 15),
            array('name' => "Busua", 'state_id' => 15),
            array('name' => "Daboase", 'state_id' => 15),
            array('name' => "Dadwen", 'state_id' => 15),
            array('name' => "Diabene", 'state_id' => 15),
            array('name' => "Dixcove", 'state_id' => 15),
            array('name' => "East Tanokrom", 'state_id' => 15),
            array('name' => "Effiakuma", 'state_id' => 15),
            array('name' => "Eikwe", 'state_id' => 15),
            array('name' => "Elubo", 'state_id' => 15),
            array('name' => "Essiama", 'state_id' => 15),
            array('name' => "Essikado", 'state_id' => 15),
            array('name' => "Essipong", 'state_id' => 15),
            array('name' => "Ewusiejo", 'state_id' => 15),
            array('name' => "Fijai", 'state_id' => 15),
            array('name' => "Funko", 'state_id' => 15),
            array('name' => "Half Assini", 'state_id' => 15),
            array('name' => "Hotopo", 'state_id' => 15),
            array('name' => "Inchaban", 'state_id' => 15),
            array('name' => "kansaworado", 'state_id' => 15),
            array('name' => "Kejabil", 'state_id' => 15),
            array('name' => "Kojokrom", 'state_id' => 15),
            array('name' => "Kwawkrom", 'state_id' => 15),
            array('name' => "Kweikuma", 'state_id' => 15),
            array('name' => "kwesimintsim", 'state_id' => 15),
            array('name' => "Manso", 'state_id' => 15),
            array('name' => "Miemia", 'state_id' => 15),
            array('name' => "Mpintsin", 'state_id' => 15),
            array('name' => "New Akwidaa", 'state_id' => 15),
            array('name' => "New Amanfu", 'state_id' => 15),
            array('name' => "New Takoradi", 'state_id' => 15),
            array('name' => "Ngyiresia", 'state_id' => 15),
            array('name' => "Nkroful", 'state_id' => 15),
            array('name' => "Nsein", 'state_id' => 15),
            array('name' => "Ntankoful", 'state_id' => 15),
            array('name' => "Nzulezo", 'state_id' => 15),
            array('name' => "Old Akwidaa", 'state_id' => 15),
            array('name' => "Prestea", 'state_id' => 15),
            array('name' => "Princess Town", 'state_id' => 15),
            array('name' => "Samreboi", 'state_id' => 15),
            array('name' => "Sekondi", 'state_id' => 15),
            array('name' => "Shama", 'state_id' => 15),
            array('name' => "Takoradi", 'state_id' => 15),
            array('name' => "Tarkwa", 'state_id' => 15),
            array('name' => "Tikobo No.1", 'state_id' => 15),
            array('name' => "Tikobo No.2", 'state_id' => 15),
            array('name' => "West Tanokrom", 'state_id' => 15),
            array('name' => "Windy Ridge", 'state_id' => 15),
            array('name' => "Attankona", 'state_id' => 16),
            array('name' => "Nkatieso", 'state_id' => 16),
            array('name' => "Abochia", 'state_id' => 16),
            array('name' => "Abusam-kwawu", 'state_id' => 16),
            array('name' => "Achimfo", 'state_id' => 16),
            array('name' => "Acquai Allah", 'state_id' => 16),
            array('name' => "Adabokrom", 'state_id' => 16),
            array('name' => "Adamase", 'state_id' => 16),
            array('name' => "Adiembra", 'state_id' => 16),
            array('name' => "Adjakaa", 'state_id' => 16),
            array('name' => "Adjoafua", 'state_id' => 16),
            array('name' => "Adukrom", 'state_id' => 16),
            array('name' => "Afere", 'state_id' => 16),
            array('name' => "Aferewa", 'state_id' => 16),
            array('name' => "Agya Mensahkrom", 'state_id' => 16),
            array('name' => "Ahibenso", 'state_id' => 16),
            array('name' => "Akaaso", 'state_id' => 16),
            array('name' => "Akaatiso", 'state_id' => 16),
            array('name' => "Akontombra", 'state_id' => 16),
            array('name' => "Akronsu", 'state_id' => 16),
            array('name' => "Amadukrom", 'state_id' => 16),
            array('name' => "Amoaya", 'state_id' => 16),
            array('name' => "Amonie", 'state_id' => 16),
            array('name' => "Anhwiafutu", 'state_id' => 16),
            array('name' => "Anhwiaso", 'state_id' => 16),
            array('name' => "Ankra-Muano", 'state_id' => 16),
            array('name' => "Antobia", 'state_id' => 16),
            array('name' => "Apronsee Mission", 'state_id' => 16),
            array('name' => "Asawinso", 'state_id' => 16),
            array('name' => "Asemkrom", 'state_id' => 16),
            array('name' => "Asikrom (Ensonnyameye)", 'state_id' => 16),
            array('name' => "Asuontaa", 'state_id' => 16),
            array('name' => "Asuopiri", 'state_id' => 16),
            array('name' => "Awaso", 'state_id' => 16),
            array('name' => "Ayidam", 'state_id' => 16),
            array('name' => "Benchema", 'state_id' => 16),
            array('name' => "Benomsuo", 'state_id' => 16),
            array('name' => "Bethlehem", 'state_id' => 16),
            array('name' => "Bibiani", 'state_id' => 16),
            array('name' => "Bibiani", 'state_id' => 16),
            array('name' => "Bodi", 'state_id' => 16),
            array('name' => "Boison", 'state_id' => 16),
            array('name' => "Boizan", 'state_id' => 16),
            array('name' => "Bokabo", 'state_id' => 16),
            array('name' => "Bonsu Nkwanta", 'state_id' => 16),
            array('name' => "Car Owner", 'state_id' => 16),
            array('name' => "Chirano", 'state_id' => 16),
            array('name' => "Dadieso", 'state_id' => 16),
            array('name' => "Denchemuosue", 'state_id' => 16),
            array('name' => "Disueano", 'state_id' => 16),
            array('name' => "Dominibo", 'state_id' => 16),
            array('name' => "Elluokrom", 'state_id' => 16),
            array('name' => "Enchi", 'state_id' => 16),
            array('name' => "Enchi", 'state_id' => 16),
            array('name' => "Essam Debiso", 'state_id' => 16),
            array('name' => "Goka", 'state_id' => 16),
            array('name' => "Gyema", 'state_id' => 16),
            array('name' => "Hene Nkwanta", 'state_id' => 16),
            array('name' => "Homgyebre", 'state_id' => 16),
            array('name' => "Hwenampori", 'state_id' => 16),
            array('name' => "Jensue", 'state_id' => 16),
            array('name' => "Juabeso Nkwanta", 'state_id' => 16),
            array('name' => "Juabeso", 'state_id' => 16),
            array('name' => "Juaboso", 'state_id' => 16),
            array('name' => "kaase", 'state_id' => 16),
            array('name' => "Kakanabo", 'state_id' => 16),
            array('name' => "Kama", 'state_id' => 16),
            array('name' => "Kankyiabo", 'state_id' => 16),
            array('name' => "Kantakrobo", 'state_id' => 16),
            array('name' => "Kefass", 'state_id' => 16),
            array('name' => "Kofi Krah", 'state_id' => 16),
            array('name' => "Kofikrom", 'state_id' => 16),
            array('name' => "Kojoaba", 'state_id' => 16),
            array('name' => "Kojofosukrom", 'state_id' => 16),
            array('name' => "Kotosaa", 'state_id' => 16),
            array('name' => "Kramokrom", 'state_id' => 16),
            array('name' => "Kunkumso", 'state_id' => 16),
            array('name' => "Kwafukaa", 'state_id' => 16),
            array('name' => "Kwaku Kyerekrom", 'state_id' => 16),
            array('name' => "Kwame Adjei Krom", 'state_id' => 16),
            array('name' => "Kwamebikrom", 'state_id' => 16),
            array('name' => "Kwawu", 'state_id' => 16),
            array('name' => "Kwesikrom", 'state_id' => 16),
            array('name' => "Kyerkyewere", 'state_id' => 16),
            array('name' => "Mafia", 'state_id' => 16),
            array('name' => "Mangoase-Punpunso", 'state_id' => 16),
            array('name' => "Mangoase", 'state_id' => 16),
            array('name' => "Mayera", 'state_id' => 16),
            array('name' => "Moshiehene Krom", 'state_id' => 16),
            array('name' => "New Abesim", 'state_id' => 16),
            array('name' => "New Achiase", 'state_id' => 16),
            array('name' => "New Nsuatre", 'state_id' => 16),
            array('name' => "New Yakasi", 'state_id' => 16),
            array('name' => "Nkrabea", 'state_id' => 16),
            array('name' => "Nkwanta", 'state_id' => 16),
            array('name' => "Nso Nyame Ye (Mireku)", 'state_id' => 16),
            array('name' => "Nsowakrom", 'state_id' => 16),
            array('name' => "Ntesano", 'state_id' => 16),
            array('name' => "Nyamebekyere No.1", 'state_id' => 16),
            array('name' => "Nyankamam", 'state_id' => 16),
            array('name' => "Okrayawkrom", 'state_id' => 16),
            array('name' => "Old Debiso", 'state_id' => 16),
            array('name' => "Old Yakasi", 'state_id' => 16),
            array('name' => "Omanpe", 'state_id' => 16),
            array('name' => "Oseikojokrom", 'state_id' => 16),
            array('name' => "Osumanikrom", 'state_id' => 16),
            array('name' => "Owusu Krom", 'state_id' => 16),
            array('name' => "Patakro", 'state_id' => 16),
            array('name' => "Pramprase", 'state_id' => 16),
            array('name' => "Proso", 'state_id' => 16),
            array('name' => "Sayerano", 'state_id' => 16),
            array('name' => "Sefwi Anhwiaso", 'state_id' => 16),
            array('name' => "Sefwi Bekwai", 'state_id' => 16),
            array('name' => "Sewum", 'state_id' => 16),
            array('name' => "Sonka No.1", 'state_id' => 16),
            array('name' => "Subri Nkwanta (Kojina)", 'state_id' => 16),
            array('name' => "Subri", 'state_id' => 16),
            array('name' => "Suiano", 'state_id' => 16),
            array('name' => "Surano", 'state_id' => 16),
            array('name' => "Tanoso-Praso", 'state_id' => 16),
            array('name' => "Wenchi", 'state_id' => 16),
            array('name' => "Yawmatwa", 'state_id' => 16),
            array('name' => "Yiwabra", 'state_id' => 16),
        );

        foreach ($cities as $city) {
            Cities::create($city);
        }
    }
}
